apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: cluster-llm-website
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cluster-llm-website
  template:
    metadata:
      labels:
        app: cluster-llm-website
    spec:
      containers:
      - name: cluster-llm-website
        image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
